import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
export const agentRuns = sqliteTable('agent_runs', {
    id: text('id').primaryKey(),
    agentId: text('agent_id').notNull(),
    agentVersion: text('agent_version'),
    status: text('status', {
        enum: ['CREATED', 'QUEUED', 'SCHEDULED', 'PENDING', 'RUNNING', 'WAITING_APPROVAL', 'WAITING_DELAY', 'RESUMING', 'COMPLETED', 'FAILED', 'CANCELLED'],
    }).notNull().default('PENDING'),
    inputJson: text('input_json').notNull().default('{}'),
    outputJson: text('output_json'),
    errorMessage: text('error_message'),
    inputTokens: integer('input_tokens').notNull().default(0),
    outputTokens: integer('output_tokens').notNull().default(0),
    totalTokens: integer('total_tokens').notNull().default(0),
    checkpointId: text('checkpoint_id'),
    correlationId: text('correlation_id'),
    parentRunId: text('parent_run_id'),
    pipelineRunId: text('pipeline_run_id'),
    deploymentId: text('deployment_id'),
    startedAt: integer('started_at', { mode: 'timestamp' }),
    completedAt: integer('completed_at', { mode: 'timestamp' }),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
    metadataJson: text('metadata_json'),
});
export const agentEvents = sqliteTable('agent_events', {
    id: text('id').primaryKey(),
    runId: text('run_id').notNull(),
    agentId: text('agent_id').notNull(),
    type: text('type').notNull(),
    dataJson: text('data_json').notNull().default('{}'),
    timestamp: integer('timestamp', { mode: 'timestamp' }).notNull(),
    sequenceNumber: integer('sequence_number').notNull(),
    redactionIncomplete: integer('redaction_incomplete', { mode: 'boolean' }).default(false),
});
export const executionCheckpoints = sqliteTable('execution_checkpoints', {
    id: text('id').primaryKey(),
    runId: text('run_id').notNull(),
    agentId: text('agent_id').notNull(),
    turnIndex: integer('turn_index').notNull(),
    messagesJson: text('messages_json').notNull().default('[]'),
    inputTokens: integer('input_tokens').notNull().default(0),
    outputTokens: integer('output_tokens').notNull().default(0),
    totalTokens: integer('total_tokens').notNull().default(0),
    agentStateJson: text('agent_state_json'),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
});
export const agentState = sqliteTable('agent_state', {
    id: text('id').primaryKey(),
    runId: text('run_id').notNull(),
    agentId: text('agent_id').notNull(),
    stateJson: text('state_json').notNull().default('{}'),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});
export const pipelineState = sqliteTable('pipeline_state', {
    id: text('id').primaryKey(),
    pipelineRunId: text('pipeline_run_id').notNull(),
    key: text('key').notNull(),
    valueJson: text('value_json').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});
export const pipelineRuns = sqliteTable('pipeline_runs', {
    id: text('id').primaryKey(),
    pipelineId: text('pipeline_id').notNull(),
    pipelineVersion: text('pipeline_version'),
    status: text('status', {
        enum: ['PENDING', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED'],
    }).notNull().default('PENDING'),
    currentStepIndex: integer('current_step_index').notNull().default(0),
    currentStepId: text('current_step_id'),
    inputJson: text('input_json').notNull().default('{}'),
    outputJson: text('output_json'),
    stepResultsJson: text('step_results_json'),
    errorMessage: text('error_message'),
    inputTokens: integer('input_tokens').notNull().default(0),
    outputTokens: integer('output_tokens').notNull().default(0),
    totalTokens: integer('total_tokens').notNull().default(0),
    correlationId: text('correlation_id'),
    startedAt: integer('started_at', { mode: 'timestamp' }),
    completedAt: integer('completed_at', { mode: 'timestamp' }),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
});
export const approvalRequests = sqliteTable('approval_requests', {
    id: text('id').primaryKey(),
    executionId: text('execution_id').notNull().default(''),
    pipelineRunId: text('pipeline_run_id'),
    stepId: text('step_id').notNull().default(''),
    runId: text('run_id'),
    agentId: text('agent_id'),
    status: text('status', {
        enum: ['PENDING', 'APPROVED', 'REJECTED', 'EXPIRED'],
    }).notNull().default('PENDING'),
    reason: text('reason').notNull().default(''),
    payloadJson: text('payload_json').notNull().default('{}'),
    promptJson: text('prompt_json').notNull().default('{}'),
    responseJson: text('response_json'),
    resolvedBy: text('resolved_by'),
    resolutionNote: text('resolution_note'),
    expiresAt: integer('expires_at', { mode: 'timestamp' }),
    resolvedAt: integer('resolved_at', { mode: 'timestamp' }),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
});
export const registryEntries = sqliteTable('registry_entries', {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    version: text('version').notNull(),
    kind: text('kind', { enum: ['agent', 'tool', 'pipeline', 'adapter'] }).notNull(),
    configJson: text('config_json').notNull().default('{}'),
    checksumSha256: text('checksum_sha256'),
    trusted: integer('trusted', { mode: 'boolean' }).notNull().default(false),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});
export const agentDefinitions = sqliteTable('agent_definitions', {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    version: text('version').notNull().default('1.0.0'),
    configJson: text('config_json').notNull().default('{}'),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});
export const deployments = sqliteTable('deployments', {
    id: text('id').primaryKey(),
    agentId: text('agent_id').notNull(),
    version: text('version').notNull(),
    status: text('status', {
        enum: ['PENDING', 'ACTIVE', 'INACTIVE', 'FAILED', 'ROLLED_BACK', 'ROLLING_BACK'],
    }).notNull().default('PENDING'),
    target: text('target', { enum: ['local', 'docker', 'railway'] }).notNull().default('local'),
    rollbackOf: text('rollback_of'),
    deployedBy: text('deployed_by'),
    imageDigest: text('image_digest'),
    configJson: text('config_json').notNull().default('{}'),
    deployedAt: integer('deployed_at', { mode: 'timestamp' }),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
});
export const memoryEntries = sqliteTable('memory_entries', {
    id: text('id').primaryKey(),
    key: text('key').notNull(),
    valueJson: text('value_json').notNull(),
    scope: text('scope', {
        enum: ['execution', 'session', 'agent', 'pipeline', 'persistent'],
    }).notNull(),
    scopeId: text('scope_id').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp' }),
    createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
});
//# sourceMappingURL=schema.js.map